### ISSUE TITLE
USER STORY: As a Site User i can be able to Register a new account, so i have a personal account and see my purchases and profile

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#1]
EPIC: Registration

As a **Site User** I can **Register a new account** so that **i have a personal account and see my purchases and profile**

**Acceptance Criteria**

- [] Users should be able to create a new account by providing at least username, and password.
- [] The registration process should be intuitive and provide appropriate feedback for errors or success.
- [] After successful registration, users should be able to log in using the newly created credentials.

**Tasks**

- [] Create the user interface for the registration form.
- [] Establish the login flow after successful registration.
- [] Create feedback messages for different states of the registration process (success, errors, etc.).
