### ISSUE TITLE
USER STORY: As a Site User i can be able to receive an email after submitting my registration form so i can verify my submision was succesfully done

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#11]
EPIC <epic>

As a **Site User** I can **be able to receive an email after submitting my registration form** so that **i can verify my submision was succesfully done**

**Acceptance Criteria**
- [ ] User receives a confirmation email promptly after submitting the registration form.
- [ ] The email content includes details confirming the successful submission.
- [ ] The confirmation email is sent to the email address provided during registration.
- [ ] If there is an issue with sending the confirmation email, the user receives a clear error message on the registration page.

**Tasks**

- [ ] Implement an email sending mechanism within the registration process.
- [ ] Generate a unique verification link for each user upon form submission.
- [ ] Develop error-handling mechanisms for any issues related to sending confirmation emails.
- Design a template email where is reflected all the data from the user
