### ISSUE TITLE
USER STORY: As a Site User i can have a personalized profile so i can have my orders, payment and shipping information

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#12]
EPIC <epic>

As a **Site User** I can **have a personalized profile** so that **i can have my orders, payment and shipping information**

**Acceptance Criteria**

- [ ] Users can view a history of their past orders in their profile.
- [ ] Each order entry includes details such as order date, items purchased
- [ ] Payment information is editable for updates and changes

**Tasks**

- [ ] Implement the ability for users to add, edit, and delete payment information.
- [ ] Implement easy navigation to the user profile from any page on the site.
- [ ] Design and implement the user interface for the profile page.
- [ ] Integrate order history functionality into the user profile.
