### ISSUE TITLE
USER STORY: As a Site User i can easily navegate through the different sections of the site

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#13]
EPIC: NAVIGATION

As a **Site User** I can **easily navigate through the different sections of the site** so that **I have a good user experience**

**Acceptance Criteria**

- [x] The site has a clear and intuitive navigation menu visible on all pages.
- [x] Menu items are logically organized and labeled for easy understanding.
- [x] Include a search function that allows users to find specific content quickly.
- [x] Search results are relevant and displayed in a user-friendly manner.

**Tasks**

- [x] Design and implement a clear and user-friendly navigation menu
- [x] Implement a functional and efficient search feature.
- [x] Implement different sections where users can have accesibility to determinated products
