### ISSUE TITLE
USER STORY: As a Site User i can add product to my shopping cart so i can purchase them

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#15]
EPIC: PRODUCT

As a **Site User** I can **add products to my shopping cart** so that **i can purchase them**

**Acceptance Criteria**

- [ ] Users can easily add products to their shopping cart from the product view.
- [ ] Confirmation is provided when a product is successfully added to the cart.
- [ ] Users can easily access their shopping cart to review selected items.

**Tasks**

- [ ] Implement the ability for users to add products to their shopping cart.
- [ ] Implementa system that alerts the user about adding items to the cart
