### ISSUE TITLE
USER STORY: As a Site User i can select size and quantity so i can choose the 

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#16]
EPIC: PRODUCTS

As a **role** I can **capability** si that **received benefit**

**Acceptance Criteria**

- [ ] Users can easily select desired Size
- [ ] Users can easily select desired Quantity

**Tasks**

- [ ] Users can select size and quantity before sending items to the cart
- [ ] Implement a dropdown menu where users can choose size
- [ ] Implement a dropdown menu where users can choose quantity
- [ ] Implement a user-friendly design for both actions
