### ISSUE TITLE
USER STORY: As a Site User I can contact the owner concerning an specific product

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#18]
EPIC: CONTACT

As a **Site User** I can **contact the owner concerning an specific product** so that **received benefit**

**Acceptance Criteria**

- [ ] The subject can be related to a general inquiry or related to a product
- [ ] In case of a product, the user can select any of the products in the shop
- [ ] The product/subject has enough information so the user can identify it

**Tasks**

- [ ] Implement a Subject input functionality where users can select either general inquiries or specific product.
- [ ] Implement a dropdown menu where user can select the product.
- [ ] Configure the email notification so is clear enough in the subject the product that the useris asking for
