### ISSUE TITLE
USER STORY: As a Site User i can get a confirmation email so im awared that the submission was submited

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#19]
EPIC: CONTACT

As a **Site User** I can **can get a confirmation email** so that **so im aware that the form was succesfully submitted**

**Acceptance Criteria**

- [ ] Users receive a confirmation message or email after successfully submitting the contact form.
- [ ] The confirmation email includes a summary of the submitted information

**Tasks**

- [ ] Configure the system to send email notifications to users informing of success submission
- [ ] Emails contain a resume of the fields covered in the form
