### ISSUE TITLE
USER STORY: As a Site User i can have a wishlist so i can have a list of items that i like

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#20]
EPIC: WISHLIST

As a **Site User** I can **have a wishlist** so that **i can have a list of items that i like**

**Acceptance Criteria**

- [ ] The wishlist should display the name, image, and brief description of each item.
- [ ] Each item in the wishlist should have a link to view more details.
- [ ] The wishlist should be persistent, meaning it should be saved even if the user logs out and logs back in.
- [ ] The wishlist should be easy to access and manage from the user's account dashboard.

**Tasks**

- [ ] Create a dedicated page for the wishlist
- [ ] Retrieve and display wishlist items on the wishlist page
- [ ] The items in the wishlist should at least show the name and image.
- [ ] Link each item in the wishlist to a page with more details.
- [ ] Ensure that the wishlist is saved for each user, even if they log out and log back in.
- [ ] Make sure the wishlist is easily accessible from the user's account dashboard.
