### ISSUE TITLE
USER STORY: As a Site User i can update my ratings so that I can reflect any changes in my experience

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#24]
EPIC: RATINGS

As a **Site User** I can **update my ratings** si that **I can reflect any changes in my experience**

**Acceptance Criteria**

- [ ] Users should be able to update their ratings for a product they have previously rated
- [ ] The updated ratings should be reflected in real-time on the product page.
- [ ] Users should receive confirmation messages upon successfully updating their ratings.
- [ ] The updated ratings and comments should persist, even if the user logs out and logs back in.
- [ ] The overall average rating for the product should be recalculated based on the updated ratings.

**Tasks**

- [ ] Provide a link or button on the product page for updating ratings.
- [ ] Implement the frontend display to show the updated average rating on the product page.
- [ ] Provide users with clear confirmation messages upon successfully updating their ratings
