### ISSUE TITLE
USER STORY: As Site Admin i can delete products from the shop so I can update the stock of the shop

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#26]
EPIC: PRODUCTS

As a **Site Admin** I can **delete products** so that **I can update the stock of the shop**

**Acceptance Criteria**
- [ ] The Site Admin can remove items from the product detail
- [ ] The product is immediately removed from the inventory and is no longer visible on the site.
- [ ] The Site Admin receives a confirmation message after successfully deleting a product.

**Tasks**
- [ ] Design and implement a "Remove" button within the product detail page accessible only to the Site Admin.
- [ ] Ensure that, upon confirmation, the product is immediately set as not visible on the site.
- [ ] Implement a confirmation message or notification for the Site Admin upon successfully removing the item.
