### ISSUE TITLE
USER STORY: As a Site Admin i can receive messages from users so i can be aware of any Inquire

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#27]
EPIC: CONTACT

As a **Site Admin** I can **receive messages** from users so that **can be aware of any Inquire**

**Acceptance Criteria**
- [ ] Site Admin can get a list of Inquires from users
- [ ]  The Site Admin receives an email or notification for each user-submitted message
- [ ] Email notification includes at least, subject, message and email adress from the user.

**Tasks**
- [ ] Create a dedicated page in the admin panel where the Site Admin can view a list of user inquiries.
- [ ] Ensure that the inquiry list includes relevant details such as subject, message, and email address from the user.
- [ ] Set up a notification system for the Site Admin to receive an email or system notification for each new user inquiry.
- [ ] Customize the email content to include key information such as subject, message, and the email address of the user.
- [ ] Implement the functionality so that Admin can reply directly from the system
