### ISSUE TITLE
As a Site User I can edit the items in my shopping cart so that i don't have to come back to the product detail

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#3]
EPIC Shopping Cart

As a **Site User** I can **edit** the items in my shopping cart so that **i don't have** to come back to the product detail

**Acceptance Criteria**
- [ ] There is an option to adjust the quantity of each product directly from the cart page.
- [ ] There is an option to adjust the size of each product directly from the cart page.
- [ ] When the quantity of an item is adjusted, the total price of the cart is automatically updated to reflect the changes
- [ ] There is an option to delete the quantity of each product directly from the cart page.

**Tasks**
- [ ] Add functionality to allow users to adjust the quantity of each item in the shopping cart.
- [ ] Add functionality to allow users to adjust the size of each item in the shopping cart.
- [ ] Implement logic to dynamically update the total price of the cart when the quantity of an item is adjusted.
- [ ] Develop functionality to enable users to remove items from their cart directly from the cart page.
