### ISSUE TITLE
As a Site User I can have a detailed view of prices so i can be aware about shipping costs and discounts

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#4]
EPIC Shopping Cart

As a **Site User** I can have a **detailed view of prices** so i can **be aware about shipping costs and discounts**

**Acceptance Criteria**
- [ ] The cart page displays the subtotal of the items in the cart before applying any discounts or shipping costs
- [ ] Clearly communicate any shipping costs associated with the order on the cart page.
- [ ] If there are any discounts applied, the cart page shows the discounted amount
- [ ] The total price, including any, shipping costs, and discounts, is prominently displayed.

**Tasks**
- [ ] Modify the cart page UI to display prices, subtotals, shipping costs, and discounts clearly.
- [ ] Implement logic to calculate and display any discounts applied to items in the cart.
- [ ] Implement logic to calculate and display shipping costs for the user.
- [ ] Implement logic to calculate and display the total price, including, shipping costs, and discounts.
