### ISSUE TITLE
As a Site User i can add my payment details to purchase my products

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#7]
EPIC Checkout

As a **Site User** I can **add my payment details** so that **i can purchase** my products

**Acceptance Criteria**

- [ ] The payment information form includes required fields such as card number, expiration date and CVV.
- [ ] Proper error handling is implemented to guide users in case of missing or incorrect information in the payment form.
- [ ] Include a clear and prominent "Proceed to Payment" button for users ready to complete the purchase.
- [ ] An invoice or checkout success must be provided with all the details concerning the payment.

**Tasks**
- [ ] Implement a confirmation message or visual indicator to inform users when they successfully add or update their payment information.
- [ ] Add a prominent "Proceed to Payment" button for users ready to move forward with the purchase.
- [ ] Design a visually appealing and informative template for the invoice or checkout success page. Include sections for order details, payment information, shipping address, and a thank-you message.
- [ ] Include a personalized thank-you message/e-mail expressing gratitude for the purchase.
