### ISSUE TITLE
USER STORY: AS a Site User i can easily log in and log out so i can access my personal account

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/90s-football-shirts#9]
EPIC REGISTRATION / USER ACCOUNT

As a **Site User** I can **easily log in and log out** so that **i can access my personal account**

**Acceptance Criteria**

- [x] There is a clear log in option on the homepage
- [x] After enetring valid credentials i can succesfully log in
- [x] When logged in, there is a visible option to "Log Out" on the homepage.
- [x] After clicking "Log Out," I am successfully logged out and redirected to the homepage.

**Tasks**
- [x] Design the "Log In" and "Log Out" buttons on the homepage.
- [x] Implement frontend components for the "Log In" form and "Log Out" button.
- [x] Implement the functionality to redirect users to the homepage after successful logout.
- [x] Set up page protection to redirect unauthenticated users to the login page when accessing protected areas.
